/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is checked in so a fresh hackathon
// clone has types before the first `next dev` run.
