[profile.default]
src = "src"
out = "out"
libs = ["../../packages/foundry/dependencies"]
script = "script"
solc = "0.8.27"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
via_ir = true
cbor_metadata = false
bytecode_hash = "none"

remappings = [
  "forge-std/=../../packages/foundry/dependencies/forge-std-1.14.0/src/",
  "shared/=../shared/"
]

[rpc_endpoints]
arc = "${ARC_TESTNET_RPC}"
